server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#ÄæÏòÉú³É
mybatis:
  type-aliases-package: com.example.demo.domain
  mapper-locations: classpath:mapper/*.xml
